---
title: "2.3 Quarto tables, figures, and stats"
format: html
---

Open the slides in a new tab [here](slides/03-quarto3.qmd){target="_blank"}.

<div>

```{=html}
<iframe class="slide-deck" src="slides/03-quarto3.html"></iframe>
```

</div>

## Exercises

Return to your quarto document with the tables.

1. Choose a table to label and caption, and then write a sentence that *cross-references* it (e.g., Table 1 shows the descriptive statistics)
3. Add a chunk where you calculate the mean number of hours of sleep on weekends (you can use the `mean()` function). Have the code print that output.
3. Now, store that value as an object in the chunk. Add it as inline text.
4. Finally, calculate the statistic directly as inline text.
5. Change the means to medians and re-render.

## Exercises part 2
6. Add a chunk with the `table1` table from the slides. Practice extracting the output using `inline_text()` as in the slides.
3. Edit or create a new table that has the median hours of sleep on weekends in it (in the overall sample).
2. From that table, pull out the that value and include in the text using `inline_text()`.

## Resources

- [Cross references](https://quarto.org/docs/authoring/cross-references.html)
-  [Inline text vignette](https://www.danieldsjoberg.com/gtsummary/articles/inline_text.html)

