{
  "hash": "72cce83dd96a48a9b26541bc5f209b2f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Quarto tables, figures, and stats\"\nformat: revealjs\nexecute: \n  eval: true\n---\n\n\n## Chunks can produce figures and tables\n\n\n::: {.cell}\n\n:::\n\n::: {#tbl-one .cell tbl-cap='This is a great table'}\n\n````{.cell-code}\n```{{r}}\n#| label: tbl-one\n#| tbl-cap: \"This is a great table\"\nknitr::kable(mtcars)\n```\n````\n\n::: {.cell-output-display}\n\n\n|                    |  mpg| cyl|  disp|  hp| drat|    wt|  qsec| vs| am| gear| carb|\n|:-------------------|----:|---:|-----:|---:|----:|-----:|-----:|--:|--:|----:|----:|\n|Mazda RX4           | 21.0|   6| 160.0| 110| 3.90| 2.620| 16.46|  0|  1|    4|    4|\n|Mazda RX4 Wag       | 21.0|   6| 160.0| 110| 3.90| 2.875| 17.02|  0|  1|    4|    4|\n|Datsun 710          | 22.8|   4| 108.0|  93| 3.85| 2.320| 18.61|  1|  1|    4|    1|\n|Hornet 4 Drive      | 21.4|   6| 258.0| 110| 3.08| 3.215| 19.44|  1|  0|    3|    1|\n|Hornet Sportabout   | 18.7|   8| 360.0| 175| 3.15| 3.440| 17.02|  0|  0|    3|    2|\n|Valiant             | 18.1|   6| 225.0| 105| 2.76| 3.460| 20.22|  1|  0|    3|    1|\n|Duster 360          | 14.3|   8| 360.0| 245| 3.21| 3.570| 15.84|  0|  0|    3|    4|\n|Merc 240D           | 24.4|   4| 146.7|  62| 3.69| 3.190| 20.00|  1|  0|    4|    2|\n|Merc 230            | 22.8|   4| 140.8|  95| 3.92| 3.150| 22.90|  1|  0|    4|    2|\n|Merc 280            | 19.2|   6| 167.6| 123| 3.92| 3.440| 18.30|  1|  0|    4|    4|\n|Merc 280C           | 17.8|   6| 167.6| 123| 3.92| 3.440| 18.90|  1|  0|    4|    4|\n|Merc 450SE          | 16.4|   8| 275.8| 180| 3.07| 4.070| 17.40|  0|  0|    3|    3|\n|Merc 450SL          | 17.3|   8| 275.8| 180| 3.07| 3.730| 17.60|  0|  0|    3|    3|\n|Merc 450SLC         | 15.2|   8| 275.8| 180| 3.07| 3.780| 18.00|  0|  0|    3|    3|\n|Cadillac Fleetwood  | 10.4|   8| 472.0| 205| 2.93| 5.250| 17.98|  0|  0|    3|    4|\n|Lincoln Continental | 10.4|   8| 460.0| 215| 3.00| 5.424| 17.82|  0|  0|    3|    4|\n|Chrysler Imperial   | 14.7|   8| 440.0| 230| 3.23| 5.345| 17.42|  0|  0|    3|    4|\n|Fiat 128            | 32.4|   4|  78.7|  66| 4.08| 2.200| 19.47|  1|  1|    4|    1|\n|Honda Civic         | 30.4|   4|  75.7|  52| 4.93| 1.615| 18.52|  1|  1|    4|    2|\n|Toyota Corolla      | 33.9|   4|  71.1|  65| 4.22| 1.835| 19.90|  1|  1|    4|    1|\n|Toyota Corona       | 21.5|   4| 120.1|  97| 3.70| 2.465| 20.01|  1|  0|    3|    1|\n|Dodge Challenger    | 15.5|   8| 318.0| 150| 2.76| 3.520| 16.87|  0|  0|    3|    2|\n|AMC Javelin         | 15.2|   8| 304.0| 150| 3.15| 3.435| 17.30|  0|  0|    3|    2|\n|Camaro Z28          | 13.3|   8| 350.0| 245| 3.73| 3.840| 15.41|  0|  0|    3|    4|\n|Pontiac Firebird    | 19.2|   8| 400.0| 175| 3.08| 3.845| 17.05|  0|  0|    3|    2|\n|Fiat X1-9           | 27.3|   4|  79.0|  66| 4.08| 1.935| 18.90|  1|  1|    4|    1|\n|Porsche 914-2       | 26.0|   4| 120.3|  91| 4.43| 2.140| 16.70|  0|  1|    5|    2|\n|Lotus Europa        | 30.4|   4|  95.1| 113| 3.77| 1.513| 16.90|  1|  1|    5|    2|\n|Ford Pantera L      | 15.8|   8| 351.0| 264| 4.22| 3.170| 14.50|  0|  1|    5|    4|\n|Ferrari Dino        | 19.7|   6| 145.0| 175| 3.62| 2.770| 15.50|  0|  1|    5|    6|\n|Maserati Bora       | 15.0|   8| 301.0| 335| 3.54| 3.570| 14.60|  0|  1|    5|    8|\n|Volvo 142E          | 21.4|   4| 121.0| 109| 4.11| 2.780| 18.60|  1|  1|    4|    2|\n\n\n:::\n:::\n\n\n## Chunks can produce figures or tables\n\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\n#| label: fig-hist\n#| fig-cap: \"This is a histogram\"\nhist(rnorm(100))\n```\n````\n\n::: {.cell-output-display}\n![This is a histogram](03-quarto3_files/figure-revealjs/fig-hist-1.png){#fig-hist width=960}\n:::\n:::\n\n\n\n## Cross-referencing\n\nYou can then refer to those with `@tbl-one` and `@fig-hist` and the Table and Figure ordering will be correct (and linked)\n\n::: larger-code\n```         \n@fig-hist contains a histogram and @tbl-one a table.\n```\n:::\n\ngets printed as:\n\n@fig-hist contains a histogram and @tbl-one a table.\n\n## Inline R\n\nAlong with just regular text, you can also run R code *within* the text:\n\n::: larger-code\n```\nThere were `r 3 + 4` participants\n```\n:::\nbecomes:\n\nThere were 7 participants\n\n## Inline R\n\nThis is helpful for reporting statistics, e.g. the sample size:\n\n::: larger-code\n```\nThere were `r nrow(nlsy)` participants\n```\n:::\nbecomes:\n\nThere were 1.2686\\times 10^{4} participants\n\n## Inline stats\n\nYou can also create an object in a chunk and then reference it later in the text\n\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\ntotal_sample <- nrow(nlsy)\n```\n````\n:::\n\n\n::: larger-code\n```\nThere were `r total_sample` participants\n```\n:::\n\n## Inline stats (aside)\n\nI often create a list of stats that I want to report in a manuscript:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstats <- list(n = nrow(data),\n              mean_age = mean(data$age))\n```\n:::\n\n\nI can then print these numbers in the text with:\n\n\n::: {.cell}\n\n:::\n\n\nThere were `` `r stats$n` `` participants with a mean age of `` `r stats$mean_age` ``.\n\nwhich turns into:\n\nThere were 1123 participants with a mean age of 43.5.\n\n## Inline stats from `{gtsummary}`\n\nWe saw very, very briefly yesterday:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gtsummary)\nincome_table <- tbl_uvregression(\n  nlsy,\n  y = income,\n  include = c(\n    sex_cat, race_eth_cat,\n    eyesight_cat, income, age_bir\n  ),\n  method = lm\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ninline_text(income_table, variable = \"age_bir\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"595 (95% CI 538, 652; p<0.001)\"\n```\n\n\n:::\n:::\n\nWe pulled a statistic from our univariate table\n\n## If we're making a table, we probably want to report numbers from it\n\n\n::: {#tbl-descr .cell tbl-cap='Descriptive statistics' output-location='slide'}\n\n````{.cell-code}\n```{{r}}\n#| label: tbl-descr\n#| tbl-cap: \"Descriptive statistics\"\n#| output-location: slide\ntable1 <- tbl_summary(\n  nlsy,\n  by = sex_cat,\n  include = c(sex_cat, race_eth_cat, region_cat,\n              eyesight_cat, glasses, age_bir)) |> \n  add_overall(last = TRUE)\ntable1\n```\n````\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yhxnphyxkk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yhxnphyxkk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yhxnphyxkk thead, #yhxnphyxkk tbody, #yhxnphyxkk tfoot, #yhxnphyxkk tr, #yhxnphyxkk td, #yhxnphyxkk th {\n  border-style: none;\n}\n\n#yhxnphyxkk p {\n  margin: 0;\n  padding: 0;\n}\n\n#yhxnphyxkk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yhxnphyxkk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yhxnphyxkk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yhxnphyxkk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yhxnphyxkk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yhxnphyxkk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yhxnphyxkk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yhxnphyxkk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yhxnphyxkk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yhxnphyxkk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yhxnphyxkk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yhxnphyxkk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yhxnphyxkk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yhxnphyxkk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yhxnphyxkk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhxnphyxkk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yhxnphyxkk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yhxnphyxkk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yhxnphyxkk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhxnphyxkk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yhxnphyxkk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhxnphyxkk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yhxnphyxkk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhxnphyxkk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yhxnphyxkk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhxnphyxkk .gt_left {\n  text-align: left;\n}\n\n#yhxnphyxkk .gt_center {\n  text-align: center;\n}\n\n#yhxnphyxkk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yhxnphyxkk .gt_font_normal {\n  font-weight: normal;\n}\n\n#yhxnphyxkk .gt_font_bold {\n  font-weight: bold;\n}\n\n#yhxnphyxkk .gt_font_italic {\n  font-style: italic;\n}\n\n#yhxnphyxkk .gt_super {\n  font-size: 65%;\n}\n\n#yhxnphyxkk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yhxnphyxkk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yhxnphyxkk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yhxnphyxkk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yhxnphyxkk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yhxnphyxkk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yhxnphyxkk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yhxnphyxkk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yhxnphyxkk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipDaGFyYWN0ZXJpc3RpYyoq&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Characteristic&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><div class='gt_from_md'><p><strong>Characteristic</strong></p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipNYWxlKiogIApOID0gNiw0MDM=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Male&lt;/strong&gt;&lt;br /&gt;&#10;N = 6,403&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KipNYWxlKiogIApOID0gNiw0MDM=\"><div class='gt_from_md'><p><strong>Male</strong><br />\nN = 6,403</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipGZW1hbGUqKiAgCk4gPSA2LDI4Mw==&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Female&lt;/strong&gt;&lt;br /&gt;&#10;N = 6,283&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KipGZW1hbGUqKiAgCk4gPSA2LDI4Mw==\"><div class='gt_from_md'><p><strong>Female</strong><br />\nN = 6,283</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipPdmVyYWxsKiogIApOID0gMTIsNjg2&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Overall&lt;/strong&gt;&lt;br /&gt;&#10;N = 12,686&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gMTIsNjg2\"><div class='gt_from_md'><p><strong>Overall</strong><br />\nN = 12,686</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">race_eth_cat</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Hispanic</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,000 (16%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,002 (16%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,002 (16%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Black</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,613 (25%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,561 (25%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3,174 (25%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Non-Black, Non-Hispanic</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,790 (59%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">3,720 (59%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">7,510 (59%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">region_cat</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Northeast</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,296 (21%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,254 (20%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,550 (20%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    North Central</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,488 (24%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,446 (23%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,934 (24%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    South</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,251 (36%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2,317 (38%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4,568 (37%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    West</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,253 (20%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,142 (19%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,395 (19%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">115</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">124</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">239</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">eyesight_cat</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Excellent</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,582 (38%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,334 (31%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,916 (35%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Very good</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,470 (35%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,500 (35%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,970 (35%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Good</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">792 (19%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,002 (23%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,794 (21%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Fair</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">267 (6.4%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">365 (8.5%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">632 (7.5%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Poor</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">47 (1.1%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">85 (2.0%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">132 (1.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,245</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,997</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4,242</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">glasses</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,566 (38%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2,328 (54%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3,894 (46%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,241</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,995</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4,236</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age_bir</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">25 (21, 29)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">22 (19, 27)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">23 (20, 28)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,652</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">3,091</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">6,743</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span> <div data-qmd-base64=\"biAoJSk7IE1lZGlhbiAoUTEsIFEzKQ==\"><div class='gt_from_md'><p>n (%); Median (Q1, Q3)</p>\n</div></div></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## I want to report some stats!\n\nThe help file for `inline_text()` is helpful and tells us that we can look at `table1$table_body` to help figure out what data to extract.\n\nHow about the median (IQR) age of the male participants at the birth of their first child?\n\n::: {.cell}\n\n```{.r .cell-code}\ninline_text(table1, variable = \"age_bir\", column = \"stat_1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"25 (21, 29)\"\n```\n\n\n:::\n:::\n\n\n## Formatting\n\nWe can add sample sizes for the  overall stats on people who wear glasses using the `pattern = ` argument:\n\n::: {.cell}\n\n```{.r .cell-code}\ninline_text(table1, variable = \"glasses\", column = \"stat_0\",\n            pattern = \"{n}/{N} ({p}%)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3,894/8450 (46%)\n```\n\n\n:::\n:::\n\n\n## Formatting for regression statistics\n\nRemove some details:\n\n::: {.cell}\n\n```{.r .cell-code}\ninline_text(income_table, variable = \"age_bir\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"595 (95% CI 538, 652; p<0.001)\"\n```\n\n\n:::\n\n```{.r .cell-code}\ninline_text(income_table, variable = \"age_bir\",\n            pattern = \"{estimate} ({conf.low}, {conf.high})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"595 (538, 652)\"\n```\n\n\n:::\n:::\n\n\n## Better yet...\n\nWe can integrate these into the text of our manuscript:\n\n::: larger-code\n```\nA greater proportion of female (`r inline_text(table1, variable = \"glasses\", column = \"stat_2\")`) than male \n\n(`r inline_text(table1, variable = \"glasses\", column = \"stat_1\")`) participants wore glasses.\n```\n:::\n\nWhich becomes:\n\nA greater proportion of female (2,328 (54%)) than male (1,566 (38%)) participants wore glasses.\n\n## Readability\n\nBecause this can be hard to read, I'd suggest storing those stats in a chunk before the text:\n\n````\n```{{r}}\nglasses_f <- inline_text(table1, variable = \"glasses\", \n                         column = \"stat_2\")\nglasses_m <- inline_text(table1, variable = \"glasses\", \n                         column = \"stat_1\")\n```\nA greater proportion of female (`r glasses_f`) than male (`r glasses_m`) participants wore glasses.\n````\n\n## Exercises\n\nReturn to the quarto document with the tables.\n\n- Choose a table to label and caption, and then write a sentence that *cross-references* it (e.g., Table 1 shows the descriptive statistics)\n- Edit or create a new table that has the median hours of sleep on weekends in it (in the overall sample).\n- Pull that value from a table.",
    "supporting": [
      "03-quarto3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}